version: '3.8'
services:
  frontend:
    container_name: datnxdevops.frontend
    image: registry.datnxdevops.site/gitlab-cicd/reactjs:staging
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    container_name: datnxdevops.backend
    image: registry.datnxdevops.site/gitlab-cicd/springboot:staging
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my_network

  db:
    container_name: datnxdevops.db
    image: mysql:8
    restart: always
    env_file:
      - .env
    volumes:
      - ./docker/data/db:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    networks:
      - my_network
